### ISSUE TITLE
Video Projector Calibration

### ISSUE THREAD

**Issue by AndreaMonzini** [stuffmatic/fSpy#14]
Hello,
i know that BLAM could be used for the Video Projector Calibration in Blender Full Screen mode:

https://github.com/stuffmatic/blam/wiki/Video-Projector-Calibration

Could fSpy be used for the Video Projector Calibration?

I am Testing fSpy as AppImage on my GNU/Linux setup but it seems quite slow ( Elementary 5.0, AMD Ryzen 1700 @ 3.7 and RX 580 , 32 GB).

Thank you for BLAM and fSpy !

**Comment by Carpetfizz** [comment]
I'm interested in doing this as well, but I don't own a projector to try it out. It seems as though the only thing fSpy needs is some kind of a "full screen" GUI so that the entire reference image can be projected in its entirety.

**Comment by stuffmatic** [comment]
Hello! I've implemented a first version of full screen mode, which I think should be enough to enable a projector calibration [workflow like this](https://github.com/stuffmatic/fSpy/blob/develop/projector_notes.md).

Since I haven't got access to a projector at the moment, I haven't tried this myself yet. If anyone is interested in trying this out, let me know and I'll make test builds.

Edit: added link to workflow document

**Comment by tornel** [comment]
Hello, i'm interested in testing it out

**Comment by stuffmatic** [comment]
I just published [1.1.0-beta.1](https://github.com/stuffmatic/fSpy/releases/tag/1.1.0-beta.1) with support for full screen mode if anyone wants to try it out. While I haven't tested this build with a projector yet, I used a similar workflow with BLAM back in the day.  I have outlined the workflow in [this document](https://github.com/stuffmatic/fSpy/blob/develop/projector_notes.md). Let me know what you think!

**Comment by tornel** [comment]
Hi, 
First, Thank you for implementing this!
however there is one issue:

currently when in full screen mode the image does not fill the screen (Check the black bars to the side of the image):
![current](https://user-images.githubusercontent.com/5472468/79226176-ee01a480-7e2b-11ea-944b-7fc3e7db8f25.png)
my guess is: because the header bar is still present the image is adjutsted to the shortest side

this is how should look (note that the header bar is still present but the image "continues" behind)
![ok](https://user-images.githubusercontent.com/5472468/79230140-2906d680-7e32-11ea-8def-71c074094310.png)

Another option is to hide the header bar altogether

PS: I tested this in Windows 10 with fSpy 1.1.0-beta.2

**Comment by stuffmatic** [comment]
Thanks for trying this out @tornel ! I've published a [new build](https://github.com/stuffmatic/fSpy/releases/tag/1.1.0-beta.3) with an attempted fix for the menu bar issue. Would be great if you could see if that solves it, since I don't have access to a windows machine at the moment.

**Comment by tornel** [comment]
Wow! that was fast! It works, the menu bar doesn't show anymore.
Thanks!

**Comment by stuffmatic** [comment]
@AndreaMonzini Do you think you could check if full screen mode (with hidden app menu) works properly on Linux as well?

**Comment by AndreaMonzini** [comment]
@stuffmatic i am at home and i do not have a projector here now. 
As soon as possible i will test it with the projector.
But i can test the fullscreen app.
Thank you for the implementation!

**Comment by AndreaMonzini** [comment]
I can confirm that fullscreen mode works ( with hidden menu bar ) on my GNU/Linux distro, Pop!_OS 19.10 !
And i can add that it is much more faster. Thank you for your work :)
