### ISSUE TITLE
Scaling issue with Blender 2.8, fSpy 1.0.1, and fSpy-Blender 1.0.1

### ISSUE THREAD

**Issue by mvittiglio** [stuffmatic/fSpy#5]
I tried using a toy box in the room to generate my reference points, etc but it seems like the scales got a bit messed up. Here is the 

https://www.youtube.com/watch?v=Hqf5xuXHBa4&t=2s
https://imgur.com/FbCfnOQ

**Comment by stuffmatic** [comment]
Had a closer look at this and managed to reproduce the issue. Seems to happen when manually changing the units of the scene. Properly setting the distance unit is on my todo list for the next release. Not sure how I managed to forget it for the first 2.8 release... 🙈

Here's an import I made without messing with the units, where the plane of width 1 matches the specified reference distance well.

<img width="596" alt="screen shot 2018-12-03 at 21 54 17" src="https://user-images.githubusercontent.com/2444852/49401119-83742b00-f746-11e8-9d1e-a6d1bd46eb9f.png">

By the way, I wish all bug reports looked like this! 🥇

**Comment by mvittiglio** [comment]
I'll try to stick to metric units then (convert on my end). Also, not sure
if you know but the update to 1.0.1 breaks compatibility with 2.79b.

Thanks for the compliment. I come from a development background and do
support work now; I WANT you to know how to break it (or tell me how I'm
doing it wrong).

I know this is a bigger question than it seems but is there an ETA on the
next release?

- Regards
- Michael Vittiglio

P Please consider the environment before printing this e-mail.

**Comment by stuffmatic** [comment]
I've released a new version of the importer that should handle reference distance units properly. The 2.79 crash should be fixed too. There's also a new version of fSpy with a more sensible list of units, so I recommend you use that.

**Comment by mvittiglio** [comment]
Holy crap! Super fast!

Thanks a bunch. Playing with it now and I'll let you know if I come into
any issues.

Heads up, I created another issue (feature request really) asking for an
"about" dialog to see what version is currently installed, etc.

- Regards
- Michael Vittiglio

P Please consider the environment before printing this e-mail.

**Comment by stuffmatic** [comment]
Closing this. Let me know if the issue persists.

**Comment by mvittiglio** [comment]
Just a heads up, I thought that the issue was still present but it seems
that the installer doesn't remove the previous version. I could just be
crazy but I'm almost certain that I ran the right installer. Just some food
for thought. Works now and thanks so much.

- Regards
- Michael Vittiglio

P Please consider the environment before printing this e-mail.

**Comment by wasd** [comment]
I am using 1.0.3 with Blender 2.79b. I save file with reference distance in centimeters, but camera position in blender imported in meters.
